spring:
  application:
    name: mc-dialog

  jpa:
    generate-ddl: false
    open-in-view: true
  datasource:
    url: jdbc:postgresql://localhost:5435/mc_dialog
    username: postgres
    password: postgres
    hikari:
      schema: dialogs
      connection-init-sql: create schema if not exists dialogs
      connection-timeout: 10000

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 8088

app:
  jwt:
    secret: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: localhost
