spring:
  application:
    name: mc-dialog

  jpa:
    generate-ddl: false
    open-in-view: true
  datasource:
    url: jdbc:postgresql://postgres_db/mc_dialog
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 8088

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://mc-eureka-conteiner:8888/eureka/
  instance:
    hostname: localhost
